name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
      run: docker-compose up -d
    - name: composer-install
      run: docker-compose exec php composer install
    - name: migration
      run: docker-compose exec php php artisan migrate
    - name: seeder
      run: docker-compose exec php php artisan db:seed
    - name: storage-link
      run: docker-compose exec php php artisan storage:link
    - name: key-generate
      run: docker-compose exec php php artisan key:generate
    - name: dump-autoload
      run: docker-compose exec php composer dump-autoload
    - name: php-unit
      run: docker-compose exec php php artisan config:clear
      run: docker-compose exec php vendor/bin/phpunit
      
