name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: docker-compose up
      run: |
            docker-compose up -d
            composer install
            docker-compose exec -T php bash -c "php artisan migrate"
            docker-compose exec -T php bash -c "php artisan db:seed"
            docker-compose exec -T php bash -c "php artisan storage:link"
            docker-compose exec -T php bash -c "php artisan key:generate"
            docker-compose exec -T php bash -c "composer dump-autoload"
            docker-compose exec -T php bash -c "php artisan config:clear"
            docker-compose exec -T php bash -c "vendor/bin/phpunit"

