name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    # 保存したシークレットたちを環境変数に設定
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2  
      run: |
        # 秘密鍵にファイル名secret_keyをつける
        echo "$SECRET_KEY" > secret_key
        # パーミッションの変更    
        chmod 600 secret_key
        # ssh接続　＞　デプロイするディレクトリに行く　＞　デプロイ
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/matching && git pull origin master"
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/matching && docker-compose exec -T php bash -c "composer install""
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/matching && docker-compose exec -T php bash -c "php artisan config:cache""
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/matching && docker-compose exec -T php bash -c "php artisan route:cache""
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/matching && docker-compose exec -T php bash -c "php artisan migrate""
        


